-- ============================================================
-- LEXCONTROL - 01_schema.sql
-- Esquema de la base de datos: creacion de DBLexControl, tablas,
-- indices, restricciones unicas y claves foraneas.
-- SIN procedimientos almacenados y SIN datos (ver 02/03/04).
-- ORDEN DE INSTALACION: 01_schema -> 02_sp_escritura_simple
--                        -> 03_sp_transaccionales -> 04_seed
-- ADVERTENCIA: ejecutar este script ELIMINA la base DBLexControl
--              si ya existe (DROP DATABASE).
-- Fuente: ScriptsDB/ (00, 01, 02, 08, 19) consolidada.
-- ============================================================

USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'DBLexControl')
BEGIN
    ALTER DATABASE DBLexControl SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DBLexControl;
END
GO

CREATE DATABASE DBLexControl;
GO

USE DBLexControl;
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

-- ------------------------------------------------------------
-- 1. Tablas, indices y FKs principales (ScriptsDB/00-LexControlDB.sql)
-- ------------------------------------------------------------
-- ============================================================
-- 1. TABLAS DE CATÁLOGOS INDIVIDUALES
-- ============================================================

-- 1.1 RAMA
CREATE TABLE RAMA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_RAMA_Nombre ON RAMA(Nombre);
CREATE INDEX IX_RAMA_Activo ON RAMA(Activo);
GO

-- 1.2 ESTADO_EXPEDIENTE
CREATE TABLE ESTADO_EXPEDIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_EXPEDIENTE_Nombre ON ESTADO_EXPEDIENTE(Nombre);
CREATE INDEX IX_ESTADO_EXPEDIENTE_Activo ON ESTADO_EXPEDIENTE(Activo);
GO

-- 1.3 TIPO_AUDIENCIA
CREATE TABLE TIPO_AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_AUDIENCIA_Nombre ON TIPO_AUDIENCIA(Nombre);
CREATE INDEX IX_TIPO_AUDIENCIA_Activo ON TIPO_AUDIENCIA(Activo);
GO

-- 1.4 ESTADO_AUDIENCIA
CREATE TABLE ESTADO_AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_AUDIENCIA_Nombre ON ESTADO_AUDIENCIA(Nombre);
CREATE INDEX IX_ESTADO_AUDIENCIA_Activo ON ESTADO_AUDIENCIA(Activo);
GO

-- 1.5 RESULTADO_AUDIENCIA
CREATE TABLE RESULTADO_AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_RESULTADO_AUDIENCIA_Nombre ON RESULTADO_AUDIENCIA(Nombre);
CREATE INDEX IX_RESULTADO_AUDIENCIA_Activo ON RESULTADO_AUDIENCIA(Activo);
GO

-- 1.6 TIPO_TRAMITE
CREATE TABLE TIPO_TRAMITE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_TRAMITE_Nombre ON TIPO_TRAMITE(Nombre);
CREATE INDEX IX_TIPO_TRAMITE_Activo ON TIPO_TRAMITE(Activo);
GO

-- 1.7 ESTADO_TRAMITE
CREATE TABLE ESTADO_TRAMITE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_TRAMITE_Nombre ON ESTADO_TRAMITE(Nombre);
CREATE INDEX IX_ESTADO_TRAMITE_Activo ON ESTADO_TRAMITE(Activo);
GO

-- 1.8 TIPO_DILIGENCIA
CREATE TABLE TIPO_DILIGENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_DILIGENCIA_Nombre ON TIPO_DILIGENCIA(Nombre);
CREATE INDEX IX_TIPO_DILIGENCIA_Activo ON TIPO_DILIGENCIA(Activo);
GO

-- 1.9 ESTADO_DILIGENCIA
CREATE TABLE ESTADO_DILIGENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_DILIGENCIA_Nombre ON ESTADO_DILIGENCIA(Nombre);
CREATE INDEX IX_ESTADO_DILIGENCIA_Activo ON ESTADO_DILIGENCIA(Activo);
GO

-- 1.10 TIPO_NOTIFICACION_OJ
CREATE TABLE TIPO_NOTIFICACION_OJ (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_NOTIFICACION_OJ_Nombre ON TIPO_NOTIFICACION_OJ(Nombre);
CREATE INDEX IX_TIPO_NOTIFICACION_OJ_Activo ON TIPO_NOTIFICACION_OJ(Activo);
GO

-- 1.11 ESTADO_NOTIFICACION_OJ
CREATE TABLE ESTADO_NOTIFICACION_OJ (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_NOTIFICACION_OJ_Nombre ON ESTADO_NOTIFICACION_OJ(Nombre);
CREATE INDEX IX_ESTADO_NOTIFICACION_OJ_Activo ON ESTADO_NOTIFICACION_OJ(Activo);
GO

-- 1.12 TIPO_PROCESO
CREATE TABLE TIPO_PROCESO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_PROCESO_Nombre ON TIPO_PROCESO(Nombre);
CREATE INDEX IX_TIPO_PROCESO_Activo ON TIPO_PROCESO(Activo);
GO

-- 1.13 ETIQUETA_NOTA
CREATE TABLE ETIQUETA_NOTA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ETIQUETA_NOTA_Nombre ON ETIQUETA_NOTA(Nombre);
CREATE INDEX IX_ETIQUETA_NOTA_Activo ON ETIQUETA_NOTA(Activo);
GO

-- 1.14 ESTADO_EVENTO
CREATE TABLE ESTADO_EVENTO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ESTADO_EVENTO_Nombre ON ESTADO_EVENTO(Nombre);
CREATE INDEX IX_ESTADO_EVENTO_Activo ON ESTADO_EVENTO(Activo);
GO

-- 1.15 TIPO_JUZGADO
CREATE TABLE TIPO_JUZGADO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_TIPO_JUZGADO_Nombre ON TIPO_JUZGADO(Nombre);
CREATE INDEX IX_TIPO_JUZGADO_Activo ON TIPO_JUZGADO(Activo);
GO

-- 1.16 ROL_PROCESAL
CREATE TABLE ROL_PROCESAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(30) NOT NULL UNIQUE,
    Valor NVARCHAR(20) NULL,
    Descripcion NVARCHAR(200) NULL,
    Color NVARCHAR(7) NULL,
    Orden INT NOT NULL DEFAULT 0,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ROL_PROCESAL_Nombre ON ROL_PROCESAL(Nombre);
CREATE INDEX IX_ROL_PROCESAL_Activo ON ROL_PROCESAL(Activo);
GO

-- ============================================================
-- 2. TABLAS BASE Y HERENCIA
-- ============================================================

-- 2.1 ROL (Roles de usuario)
CREATE TABLE ROL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(30) NOT NULL UNIQUE,
    Descripcion NVARCHAR(200) NULL,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_ROL_Nombre ON ROL(Nombre);
CREATE INDEX IX_ROL_Activo ON ROL(Activo);
GO

-- 2.2 PERSONA
CREATE TABLE PERSONA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NombreCompleto NVARCHAR(100) NOT NULL,
    DPI NVARCHAR(20) NULL,
    TelefonoPrincipal NVARCHAR(20) NULL,
    EmailPrincipal NVARCHAR(100) NULL,
    Direccion NVARCHAR(200) NULL,
    FechaNacimiento DATE NULL,
    Genero CHAR(1) NULL,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    UsuarioCreacion_ID INT NULL,
    UsuarioModificacion_ID INT NULL,
    CONSTRAINT CHK_PERSONA_Genero CHECK (Genero IN ('M', 'F', 'O'))
);
CREATE INDEX IX_PERSONA_Nombre ON PERSONA(NombreCompleto);
-- Único FILTRADO: admite varios DPI nulos y conserva unicidad de DPIs reales.
CREATE UNIQUE INDEX UX_PERSONA_DPI ON PERSONA(DPI) WHERE DPI IS NOT NULL;
CREATE INDEX IX_PERSONA_Email ON PERSONA(EmailPrincipal);
CREATE INDEX IX_PERSONA_Activo ON PERSONA(Activo);
GO

-- 2.3 USUARIO
CREATE TABLE USUARIO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Persona_ID INT NOT NULL UNIQUE,
    Rol_ID INT NOT NULL,
    Usuario NVARCHAR(50) NOT NULL UNIQUE,
    ContraseñaHash NVARCHAR(255) NOT NULL,
    UltimoAcceso DATETIME NULL,
    IntentosFallidos INT NOT NULL DEFAULT 0,
    Bloqueado BIT NOT NULL DEFAULT 0,
    FechaBloqueo DATETIME NULL,
    CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (Persona_ID) REFERENCES PERSONA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (Rol_ID) REFERENCES ROL(ID)
);
CREATE INDEX IX_USUARIO_Usuario ON USUARIO(Usuario);
CREATE INDEX IX_USUARIO_Rol ON USUARIO(Rol_ID);
CREATE INDEX IX_USUARIO_Persona ON USUARIO(Persona_ID);
GO

-- 2.4 CLIENTE
CREATE TABLE CLIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Persona_ID INT NOT NULL UNIQUE,
    TelefonoSecundario NVARCHAR(20) NULL,
    EmailSecundario NVARCHAR(100) NULL,
    TipoCliente NVARCHAR(20) NULL DEFAULT 'Particular',
    Notas NVARCHAR(500) NULL,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (Persona_ID) REFERENCES PERSONA(ID) ON DELETE CASCADE
);
CREATE INDEX IX_CLIENTE_Persona ON CLIENTE(Persona_ID);
CREATE INDEX IX_CLIENTE_Tipo ON CLIENTE(TipoCliente);
CREATE INDEX IX_CLIENTE_Activo ON CLIENTE(Activo);
GO

-- ============================================================
-- 3. TABLAS GEOGRÁFICAS
-- ============================================================

-- 3.1 DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(50) NOT NULL,
    Codigo NVARCHAR(5) NULL,
    Pais NVARCHAR(50) NOT NULL DEFAULT 'Guatemala',
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
);
CREATE INDEX IX_DEPARTAMENTO_Nombre ON DEPARTAMENTO(Nombre);
GO

-- 3.2 MUNICIPIO
CREATE TABLE MUNICIPIO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Departamento_ID INT NOT NULL,
    Nombre NVARCHAR(50) NOT NULL,
    CodigoPostal NVARCHAR(10) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_MUNICIPIO_DEPARTAMENTO FOREIGN KEY (Departamento_ID) REFERENCES DEPARTAMENTO(ID)
);
CREATE INDEX IX_MUNICIPIO_Departamento ON MUNICIPIO(Departamento_ID);
CREATE INDEX IX_MUNICIPIO_Nombre ON MUNICIPIO(Nombre);
GO

-- 3.3 JUZGADO
CREATE TABLE JUZGADO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Municipio_ID INT NOT NULL,
    Tipo_Juzgado_ID INT NOT NULL,
    Nombre NVARCHAR(100) NOT NULL,
    Direccion NVARCHAR(200) NULL,
    Telefono NVARCHAR(20) NULL,
    Email NVARCHAR(100) NULL,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_JUZGADO_MUNICIPIO FOREIGN KEY (Municipio_ID) REFERENCES MUNICIPIO(ID),
    CONSTRAINT FK_JUZGADO_TIPO_JUZGADO FOREIGN KEY (Tipo_Juzgado_ID) REFERENCES TIPO_JUZGADO(ID)
);
CREATE INDEX IX_JUZGADO_Municipio ON JUZGADO(Municipio_ID);
CREATE INDEX IX_JUZGADO_Tipo ON JUZGADO(Tipo_Juzgado_ID);
CREATE INDEX IX_JUZGADO_Nombre ON JUZGADO(Nombre);
CREATE INDEX IX_JUZGADO_Activo ON JUZGADO(Activo);
GO

-- ============================================================
-- 4. TABLAS TRANSACCIONALES
-- ============================================================

-- 4.1 EXPEDIENTE
CREATE TABLE EXPEDIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Cliente_ID INT NOT NULL,
    Rol_Procesal_ID INT NOT NULL,
    NoExpediente NVARCHAR(50) NOT NULL UNIQUE,
    Rama_ID INT NOT NULL,
    TipoProceso NVARCHAR(50) NULL,
    Juzgado_ID INT NOT NULL,
    FechaIngreso DATE NOT NULL DEFAULT GETDATE(),
    Estado_ID INT NOT NULL,
    Descripcion NVARCHAR(500) NULL,
    NotasInternas NVARCHAR(1000) NULL,
    FechaCierre DATE NULL,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_EXPEDIENTE_CLIENTE FOREIGN KEY (Cliente_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_EXPEDIENTE_ROL_PROCESAL FOREIGN KEY (Rol_Procesal_ID) REFERENCES ROL_PROCESAL(ID),
    CONSTRAINT FK_EXPEDIENTE_RAMA FOREIGN KEY (Rama_ID) REFERENCES RAMA(ID),
    CONSTRAINT FK_EXPEDIENTE_ESTADO_EXPEDIENTE FOREIGN KEY (Estado_ID) REFERENCES ESTADO_EXPEDIENTE(ID),
    CONSTRAINT FK_EXPEDIENTE_JUZGADO FOREIGN KEY (Juzgado_ID) REFERENCES JUZGADO(ID),
    CONSTRAINT FK_EXPEDIENTE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_EXPEDIENTE_Cliente ON EXPEDIENTE(Cliente_ID);
CREATE INDEX IX_EXPEDIENTE_NoExpediente ON EXPEDIENTE(NoExpediente);
CREATE INDEX IX_EXPEDIENTE_Rama ON EXPEDIENTE(Rama_ID);
CREATE INDEX IX_EXPEDIENTE_Estado ON EXPEDIENTE(Estado_ID);
CREATE INDEX IX_EXPEDIENTE_Juzgado ON EXPEDIENTE(Juzgado_ID);
CREATE INDEX IX_EXPEDIENTE_Usuario ON EXPEDIENTE(Usuario_ID);
CREATE INDEX IX_EXPEDIENTE_FechaIngreso ON EXPEDIENTE(FechaIngreso);
GO

-- 4.2 PARTE_PROCESAL
CREATE TABLE PARTE_PROCESAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    Tipo NVARCHAR(20) NOT NULL,
    NombreCompleto NVARCHAR(100) NOT NULL,
    DPI NVARCHAR(20) NULL,
    Telefono NVARCHAR(20) NULL,
    AbogadoDefensor NVARCHAR(100) NULL,
    Rol NVARCHAR(50) NULL,
    Descripcion NVARCHAR(200) NULL,
    Activo BIT NOT NULL DEFAULT 1,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_PARTE_PROCESAL_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE
);
CREATE INDEX IX_PARTE_PROCESAL_Expediente ON PARTE_PROCESAL(Expediente_ID);
CREATE INDEX IX_PARTE_PROCESAL_Tipo ON PARTE_PROCESAL(Tipo);
CREATE INDEX IX_PARTE_PROCESAL_Nombre ON PARTE_PROCESAL(NombreCompleto);
GO

-- 4.3 AUDIENCIA
CREATE TABLE AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    Fecha DATE NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraFin TIME NULL,
    Tipo_ID INT NOT NULL,
    Juzgado_ID INT NOT NULL,
    Sala NVARCHAR(50) NULL,
    Estado_ID INT NOT NULL,
    Resultado_ID INT NULL,
    DescripcionResultado NVARCHAR(1000) NULL,
    ProximaActuacion NVARCHAR(200) NULL,
    Notas NVARCHAR(500) NULL,
    Documentos NVARCHAR(500) NULL,
    Usuario_Creacion_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_AUDIENCIA_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AUDIENCIA_TIPO_AUDIENCIA FOREIGN KEY (Tipo_ID) REFERENCES TIPO_AUDIENCIA(ID),
    CONSTRAINT FK_AUDIENCIA_ESTADO_AUDIENCIA FOREIGN KEY (Estado_ID) REFERENCES ESTADO_AUDIENCIA(ID),
    CONSTRAINT FK_AUDIENCIA_RESULTADO_AUDIENCIA FOREIGN KEY (Resultado_ID) REFERENCES RESULTADO_AUDIENCIA(ID),
    CONSTRAINT FK_AUDIENCIA_JUZGADO FOREIGN KEY (Juzgado_ID) REFERENCES JUZGADO(ID),
    CONSTRAINT FK_AUDIENCIA_USUARIO FOREIGN KEY (Usuario_Creacion_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_AUDIENCIA_Expediente ON AUDIENCIA(Expediente_ID);
CREATE INDEX IX_AUDIENCIA_Fecha ON AUDIENCIA(Fecha);
CREATE INDEX IX_AUDIENCIA_Juzgado ON AUDIENCIA(Juzgado_ID);
CREATE INDEX IX_AUDIENCIA_Estado ON AUDIENCIA(Estado_ID);
CREATE INDEX IX_AUDIENCIA_Tipo ON AUDIENCIA(Tipo_ID);
GO

-- 4.4 TRAMITE
CREATE TABLE TRAMITE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    Tipo_ID INT NOT NULL,
    Institucion NVARCHAR(100) NOT NULL,
    FechaIngreso DATE NOT NULL DEFAULT GETDATE(),
    Estado_ID INT NOT NULL,
    Descripcion NVARCHAR(500) NULL,
    OficioReferencia NVARCHAR(50) NULL,
    NotasInternas NVARCHAR(500) NULL,
    DocumentosAdjuntos NVARCHAR(500) NULL,
    FechaResolucion DATE NULL,
    ResumenResolucion NVARCHAR(500) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaUltimaActualizacion DATETIME NULL,
    CONSTRAINT FK_TRAMITE_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRAMITE_TIPO_TRAMITE FOREIGN KEY (Tipo_ID) REFERENCES TIPO_TRAMITE(ID),
    CONSTRAINT FK_TRAMITE_ESTADO_TRAMITE FOREIGN KEY (Estado_ID) REFERENCES ESTADO_TRAMITE(ID)
);
CREATE INDEX IX_TRAMITE_Expediente ON TRAMITE(Expediente_ID);
CREATE INDEX IX_TRAMITE_FechaIngreso ON TRAMITE(FechaIngreso);
CREATE INDEX IX_TRAMITE_Estado ON TRAMITE(Estado_ID);
CREATE INDEX IX_TRAMITE_Institucion ON TRAMITE(Institucion);
GO

-- 4.5 DILIGENCIA
CREATE TABLE DILIGENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NULL,
    Cliente_ID INT NULL,
    Tipo_ID INT NOT NULL,
    Titulo NVARCHAR(200) NOT NULL,
    Descripcion NVARCHAR(500) NULL,
    Fecha DATE NOT NULL,
    HoraInicio TIME NULL,
    DiaCompleto BIT NOT NULL DEFAULT 0,
    Ubicacion NVARCHAR(200) NULL,
    Oficina NVARCHAR(100) NULL,
    Estado_ID INT NOT NULL,
    Notas NVARCHAR(500) NULL,
    TiempoDedicado NVARCHAR(20) NULL,
    RecordatorioMinutos INT NULL DEFAULT 30,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DILIGENCIA_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_DILIGENCIA_CLIENTE FOREIGN KEY (Cliente_ID) REFERENCES CLIENTE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_DILIGENCIA_TIPO_DILIGENCIA FOREIGN KEY (Tipo_ID) REFERENCES TIPO_DILIGENCIA(ID),
    CONSTRAINT FK_DILIGENCIA_ESTADO_DILIGENCIA FOREIGN KEY (Estado_ID) REFERENCES ESTADO_DILIGENCIA(ID),
    CONSTRAINT FK_DILIGENCIA_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CHK_DILIGENCIA_ENTIDAD CHECK (Expediente_ID IS NOT NULL OR Cliente_ID IS NOT NULL)
);
CREATE INDEX IX_DILIGENCIA_Expediente ON DILIGENCIA(Expediente_ID);
CREATE INDEX IX_DILIGENCIA_Cliente ON DILIGENCIA(Cliente_ID);
CREATE INDEX IX_DILIGENCIA_Fecha ON DILIGENCIA(Fecha);
CREATE INDEX IX_DILIGENCIA_Estado ON DILIGENCIA(Estado_ID);
CREATE INDEX IX_DILIGENCIA_Usuario ON DILIGENCIA(Usuario_ID);
GO

-- 4.6 NOTIFICACION_OJ
CREATE TABLE NOTIFICACION_OJ (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    Juzgado_ID INT NOT NULL,
    FechaRecepcion DATE NOT NULL DEFAULT GETDATE(),
    Tipo_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NULL,
    Resumen NVARCHAR(500) NULL,
    Estado_ID INT NOT NULL,
    NumeroExpedienteOJ NVARCHAR(50) NULL,
    PDF_Ruta NVARCHAR(500) NULL,
    DuplicadoDe_ID INT NULL,
    Notas NVARCHAR(500) NULL,
    EsResolucion BIT NOT NULL DEFAULT 0,
    NumeroResolucion NVARCHAR(50) NULL,
    Favorable BIT NULL,
    FechaAtencion DATE NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_NOTIFICACION_OJ_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIFICACION_OJ_JUZGADO FOREIGN KEY (Juzgado_ID) REFERENCES JUZGADO(ID),
    CONSTRAINT FK_NOTIFICACION_OJ_TIPO_NOTIFICACION_OJ FOREIGN KEY (Tipo_ID) REFERENCES TIPO_NOTIFICACION_OJ(ID),
    CONSTRAINT FK_NOTIFICACION_OJ_ESTADO_NOTIFICACION_OJ FOREIGN KEY (Estado_ID) REFERENCES ESTADO_NOTIFICACION_OJ(ID),
    CONSTRAINT FK_NOTIFICACION_OJ_DUPLICADO FOREIGN KEY (DuplicadoDe_ID) REFERENCES NOTIFICACION_OJ(ID)
);
CREATE INDEX IX_NOTIFICACION_OJ_Expediente ON NOTIFICACION_OJ(Expediente_ID);
CREATE INDEX IX_NOTIFICACION_OJ_Juzgado ON NOTIFICACION_OJ(Juzgado_ID);
CREATE INDEX IX_NOTIFICACION_OJ_FechaRecepcion ON NOTIFICACION_OJ(FechaRecepcion);
CREATE INDEX IX_NOTIFICACION_OJ_Estado ON NOTIFICACION_OJ(Estado_ID);
CREATE INDEX IX_NOTIFICACION_OJ_Duplicado ON NOTIFICACION_OJ(DuplicadoDe_ID);
GO

-- ============================================================
-- 5. TABLAS DE EVENTOS (AGENDA)
-- ============================================================

-- 5.1 EVENTO_BASE
CREATE TABLE EVENTO_BASE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NULL,
    Cliente_ID INT NULL,
    Titulo NVARCHAR(200) NOT NULL,
    Descripcion NVARCHAR(500) NULL,
    Fecha DATE NOT NULL,
    HoraInicio TIME NOT NULL,
    HoraFin TIME NULL,
    DiaCompleto BIT NOT NULL DEFAULT 0,
    Ubicacion NVARCHAR(200) NULL,
    Prioridad INT NOT NULL DEFAULT 0,
    ColorEvento NVARCHAR(7) NULL,
    Estado_ID INT NOT NULL,
    TipoEvento NVARCHAR(20) NOT NULL,
    EsInterno BIT NOT NULL DEFAULT 0,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CreadoPor INT NOT NULL,
    CONSTRAINT FK_EVENTO_BASE_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EVENTO_BASE_CLIENTE FOREIGN KEY (Cliente_ID) REFERENCES CLIENTE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EVENTO_BASE_ESTADO_EVENTO FOREIGN KEY (Estado_ID) REFERENCES ESTADO_EVENTO(ID),
    CONSTRAINT FK_EVENTO_BASE_USUARIO FOREIGN KEY (CreadoPor) REFERENCES USUARIO(ID),
    CONSTRAINT CHK_EVENTO_ENTIDAD CHECK (Expediente_ID IS NOT NULL OR Cliente_ID IS NOT NULL OR EsInterno = 1),
    CONSTRAINT CHK_EVENTO_TIPO CHECK (TipoEvento IN ('Audiencia', 'Plazo', 'Diligencia', 'Cita', 'Otro'))
);
CREATE INDEX IX_EVENTO_BASE_Fecha ON EVENTO_BASE(Fecha);
CREATE INDEX IX_EVENTO_BASE_Expediente ON EVENTO_BASE(Expediente_ID);
CREATE INDEX IX_EVENTO_BASE_Cliente ON EVENTO_BASE(Cliente_ID);
CREATE INDEX IX_EVENTO_BASE_Estado ON EVENTO_BASE(Estado_ID);
CREATE INDEX IX_EVENTO_BASE_Tipo ON EVENTO_BASE(TipoEvento);
CREATE INDEX IX_EVENTO_BASE_Prioridad ON EVENTO_BASE(Prioridad);
GO

-- 5.2 EVENTO_AUDIENCIA
CREATE TABLE EVENTO_AUDIENCIA (
    Evento_ID INT PRIMARY KEY,
    TipoAudiencia NVARCHAR(30) NOT NULL,
    Juzgado_ID INT NULL,
    Secretario_ID INT NULL,
    NumeroExpedienteJudicial NVARCHAR(50) NULL,
    Resolucion NVARCHAR(MAX) NULL,
    AsistenciaAbogado BIT NULL,
    AsistenciaCliente BIT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_EVENTO_AUDIENCIA_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EVENTO_AUDIENCIA_JUZGADO FOREIGN KEY (Juzgado_ID) REFERENCES JUZGADO(ID),
    CONSTRAINT FK_EVENTO_AUDIENCIA_USUARIO FOREIGN KEY (Secretario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_EVENTO_AUDIENCIA_Juzgado ON EVENTO_AUDIENCIA(Juzgado_ID);
GO

-- 5.3 EVENTO_PLAZO
CREATE TABLE EVENTO_PLAZO (
    Evento_ID INT PRIMARY KEY,
    TipoPlazo NVARCHAR(20) NOT NULL,
    DiasHabiles INT NOT NULL,
    FechaInicioConteo DATE NOT NULL,
    FechaVencimiento DATE NOT NULL,
    DiasRestantes INT NULL,
    Notificado BIT NOT NULL DEFAULT 0,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_EVENTO_PLAZO_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_EVENTO_PLAZO_DIAS CHECK (DiasHabiles > 0),
    CONSTRAINT CHK_EVENTO_PLAZO_FECHAS CHECK (FechaVencimiento >= FechaInicioConteo)
);
CREATE INDEX IX_EVENTO_PLAZO_Vencimiento ON EVENTO_PLAZO(FechaVencimiento);
GO

-- 5.4 EVENTO_DILIGENCIA
CREATE TABLE EVENTO_DILIGENCIA (
    Evento_ID INT PRIMARY KEY,
    TipoDiligencia NVARCHAR(30) NOT NULL,
    Resultado NVARCHAR(MAX) NULL,
    NotasAdicionales NVARCHAR(500) NULL,
    TiempoDedicado NVARCHAR(20) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_EVENTO_DILIGENCIA_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE CASCADE
);
GO

-- 5.5 EVENTO_ASISTENTES
CREATE TABLE EVENTO_ASISTENTES (
    Evento_ID INT NOT NULL,
    Usuario_ID INT NOT NULL,
    Rol NVARCHAR(30) NOT NULL,
    Confirmado BIT NOT NULL DEFAULT 0,
    Notificado BIT NOT NULL DEFAULT 0,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_EVENTO_ASISTENTES PRIMARY KEY (Evento_ID, Usuario_ID),
    CONSTRAINT FK_EVENTO_ASISTENTES_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EVENTO_ASISTENTES_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CHK_EVENTO_ASISTENTES_Rol CHECK (Rol IN ('Titular', 'Suplente', 'Asociado', 'Secretario', 'Externo'))
);
CREATE INDEX IX_EVENTO_ASISTENTES_Evento ON EVENTO_ASISTENTES(Evento_ID);
CREATE INDEX IX_EVENTO_ASISTENTES_Usuario ON EVENTO_ASISTENTES(Usuario_ID);
GO

-- 5.6 EVENTO_RECORDATORIOS
CREATE TABLE EVENTO_RECORDATORIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Evento_ID INT NOT NULL,
    DiasAnticipacion INT NOT NULL,
    TipoNotificacion NVARCHAR(20) NOT NULL,
    Enviado BIT NOT NULL DEFAULT 0,
    FechaEnvio DATETIME NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_EVENTO_RECORDATORIOS_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_EVENTO_RECORDATORIOS_Dias CHECK (DiasAnticipacion IN (1, 2, 3, 5, 7, 15, 30)),
    CONSTRAINT CHK_EVENTO_RECORDATORIOS_Tipo CHECK (TipoNotificacion IN ('Email', 'Push', 'SMS', 'Dashboard'))
);
CREATE INDEX IX_EVENTO_RECORDATORIOS_Evento ON EVENTO_RECORDATORIOS(Evento_ID);
CREATE INDEX IX_EVENTO_RECORDATORIOS_Enviado ON EVENTO_RECORDATORIOS(Enviado, DiasAnticipacion);
GO

-- ============================================================
-- 6. TABLAS DE NOTAS INDIVIDUALES
-- ============================================================

-- 6.1 NOTA_EXPEDIENTE
CREATE TABLE NOTA_EXPEDIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_EXPEDIENTE_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_EXPEDIENTE_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_EXPEDIENTE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_EXPEDIENTE_Expediente ON NOTA_EXPEDIENTE(Expediente_ID);
CREATE INDEX IX_NOTA_EXPEDIENTE_Usuario ON NOTA_EXPEDIENTE(Usuario_ID);
CREATE INDEX IX_NOTA_EXPEDIENTE_Etiqueta ON NOTA_EXPEDIENTE(Etiqueta_ID);
GO

-- 6.2 NOTA_CLIENTE
CREATE TABLE NOTA_CLIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Cliente_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_CLIENTE_CLIENTE FOREIGN KEY (Cliente_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_CLIENTE_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_CLIENTE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_CLIENTE_Cliente ON NOTA_CLIENTE(Cliente_ID);
CREATE INDEX IX_NOTA_CLIENTE_Usuario ON NOTA_CLIENTE(Usuario_ID);
CREATE INDEX IX_NOTA_CLIENTE_Etiqueta ON NOTA_CLIENTE(Etiqueta_ID);
GO

-- 6.3 NOTA_AUDIENCIA
CREATE TABLE NOTA_AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Audiencia_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_AUDIENCIA_AUDIENCIA FOREIGN KEY (Audiencia_ID) REFERENCES AUDIENCIA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_AUDIENCIA_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_AUDIENCIA_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_AUDIENCIA_Audiencia ON NOTA_AUDIENCIA(Audiencia_ID);
CREATE INDEX IX_NOTA_AUDIENCIA_Usuario ON NOTA_AUDIENCIA(Usuario_ID);
CREATE INDEX IX_NOTA_AUDIENCIA_Etiqueta ON NOTA_AUDIENCIA(Etiqueta_ID);
GO

-- 6.4 NOTA_TRAMITE
CREATE TABLE NOTA_TRAMITE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Tramite_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_TRAMITE_TRAMITE FOREIGN KEY (Tramite_ID) REFERENCES TRAMITE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_TRAMITE_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_TRAMITE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_TRAMITE_Tramite ON NOTA_TRAMITE(Tramite_ID);
CREATE INDEX IX_NOTA_TRAMITE_Usuario ON NOTA_TRAMITE(Usuario_ID);
CREATE INDEX IX_NOTA_TRAMITE_Etiqueta ON NOTA_TRAMITE(Etiqueta_ID);
GO

-- 6.5 NOTA_DILIGENCIA
CREATE TABLE NOTA_DILIGENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Diligencia_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_DILIGENCIA_DILIGENCIA FOREIGN KEY (Diligencia_ID) REFERENCES DILIGENCIA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_DILIGENCIA_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_DILIGENCIA_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_DILIGENCIA_Diligencia ON NOTA_DILIGENCIA(Diligencia_ID);
CREATE INDEX IX_NOTA_DILIGENCIA_Usuario ON NOTA_DILIGENCIA(Usuario_ID);
CREATE INDEX IX_NOTA_DILIGENCIA_Etiqueta ON NOTA_DILIGENCIA(Etiqueta_ID);
GO

-- 6.6 NOTA_NOTIFICACION
CREATE TABLE NOTA_NOTIFICACION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Notificacion_ID INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Etiqueta_ID INT NULL,
    Fijado BIT NOT NULL DEFAULT 0,
    Prioritario BIT NOT NULL DEFAULT 0,
    Usuario_ID INT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    FechaModificacion DATETIME NULL,
    CONSTRAINT FK_NOTA_NOTIFICACION_NOTIFICACION_OJ FOREIGN KEY (Notificacion_ID) REFERENCES NOTIFICACION_OJ(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTA_NOTIFICACION_ETIQUETA_NOTA FOREIGN KEY (Etiqueta_ID) REFERENCES ETIQUETA_NOTA(ID),
    CONSTRAINT FK_NOTA_NOTIFICACION_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_NOTA_NOTIFICACION_Notificacion ON NOTA_NOTIFICACION(Notificacion_ID);
CREATE INDEX IX_NOTA_NOTIFICACION_Usuario ON NOTA_NOTIFICACION(Usuario_ID);
CREATE INDEX IX_NOTA_NOTIFICACION_Etiqueta ON NOTA_NOTIFICACION(Etiqueta_ID);
GO

-- ============================================================
-- 7. TABLAS DE DOCUMENTOS INDIVIDUALES
-- ============================================================

-- 7.1 DOC_EXPEDIENTE
CREATE TABLE DOC_EXPEDIENTE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    NombreArchivo NVARCHAR(200) NOT NULL,
    RutaArchivo NVARCHAR(500) NOT NULL,
    TipoArchivo NVARCHAR(20) NOT NULL,
    Tamano BIGINT NULL,
    Descripcion NVARCHAR(200) NULL,
    Usuario_ID INT NOT NULL,
    FechaSubida DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DOC_EXPEDIENTE_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_EXPEDIENTE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_DOC_EXPEDIENTE_Expediente ON DOC_EXPEDIENTE(Expediente_ID);
CREATE INDEX IX_DOC_EXPEDIENTE_Usuario ON DOC_EXPEDIENTE(Usuario_ID);
GO

-- 7.2 DOC_AUDIENCIA
CREATE TABLE DOC_AUDIENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Audiencia_ID INT NOT NULL,
    NombreArchivo NVARCHAR(200) NOT NULL,
    RutaArchivo NVARCHAR(500) NOT NULL,
    TipoArchivo NVARCHAR(20) NOT NULL,
    Tamano BIGINT NULL,
    Descripcion NVARCHAR(200) NULL,
    Usuario_ID INT NOT NULL,
    FechaSubida DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DOC_AUDIENCIA_AUDIENCIA FOREIGN KEY (Audiencia_ID) REFERENCES AUDIENCIA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_AUDIENCIA_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_DOC_AUDIENCIA_Audiencia ON DOC_AUDIENCIA(Audiencia_ID);
CREATE INDEX IX_DOC_AUDIENCIA_Usuario ON DOC_AUDIENCIA(Usuario_ID);
GO

-- 7.3 DOC_TRAMITE
CREATE TABLE DOC_TRAMITE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Tramite_ID INT NOT NULL,
    NombreArchivo NVARCHAR(200) NOT NULL,
    RutaArchivo NVARCHAR(500) NOT NULL,
    TipoArchivo NVARCHAR(20) NOT NULL,
    Tamano BIGINT NULL,
    Descripcion NVARCHAR(200) NULL,
    Usuario_ID INT NOT NULL,
    FechaSubida DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DOC_TRAMITE_TRAMITE FOREIGN KEY (Tramite_ID) REFERENCES TRAMITE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_TRAMITE_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_DOC_TRAMITE_Tramite ON DOC_TRAMITE(Tramite_ID);
CREATE INDEX IX_DOC_TRAMITE_Usuario ON DOC_TRAMITE(Usuario_ID);
GO

-- 7.4 DOC_DILIGENCIA
CREATE TABLE DOC_DILIGENCIA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Diligencia_ID INT NOT NULL,
    NombreArchivo NVARCHAR(200) NOT NULL,
    RutaArchivo NVARCHAR(500) NOT NULL,
    TipoArchivo NVARCHAR(20) NOT NULL,
    Tamano BIGINT NULL,
    Descripcion NVARCHAR(200) NULL,
    Usuario_ID INT NOT NULL,
    FechaSubida DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DOC_DILIGENCIA_DILIGENCIA FOREIGN KEY (Diligencia_ID) REFERENCES DILIGENCIA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_DILIGENCIA_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_DOC_DILIGENCIA_Diligencia ON DOC_DILIGENCIA(Diligencia_ID);
CREATE INDEX IX_DOC_DILIGENCIA_Usuario ON DOC_DILIGENCIA(Usuario_ID);
GO

-- 7.5 DOC_NOTIFICACION
CREATE TABLE DOC_NOTIFICACION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Notificacion_ID INT NOT NULL,
    NombreArchivo NVARCHAR(200) NOT NULL,
    RutaArchivo NVARCHAR(500) NOT NULL,
    TipoArchivo NVARCHAR(20) NOT NULL,
    Tamano BIGINT NULL,
    Descripcion NVARCHAR(200) NULL,
    Usuario_ID INT NOT NULL,
    FechaSubida DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_DOC_NOTIFICACION_NOTIFICACION_OJ FOREIGN KEY (Notificacion_ID) REFERENCES NOTIFICACION_OJ(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_NOTIFICACION_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_DOC_NOTIFICACION_Notificacion ON DOC_NOTIFICACION(Notificacion_ID);
CREATE INDEX IX_DOC_NOTIFICACION_Usuario ON DOC_NOTIFICACION(Usuario_ID);
GO

-- ============================================================
-- 8. TABLAS DE GESTIÓN
-- ============================================================

-- 8.1 ALERTA
CREATE TABLE ALERTA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Expediente_ID INT NOT NULL,
    TipoAlerta NVARCHAR(30) NOT NULL,
    Referencia_ID INT NOT NULL,
    Referencia_Tabla NVARCHAR(30) NOT NULL,
    Titulo NVARCHAR(200) NOT NULL,
    Descripcion NVARCHAR(500) NULL,
    FechaAlerta DATE NOT NULL,
    Estado NVARCHAR(20) NOT NULL DEFAULT 'Activa',
    Leida BIT NOT NULL DEFAULT 0,
    Evento_ID INT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_ALERTA_EXPEDIENTE FOREIGN KEY (Expediente_ID) REFERENCES EXPEDIENTE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALERTA_EVENTO_BASE FOREIGN KEY (Evento_ID) REFERENCES EVENTO_BASE(ID) ON DELETE SET NULL,
    CONSTRAINT CHK_ALERTA_Estado CHECK (Estado IN ('Activa', 'Atendida', 'Cancelada'))
);
CREATE INDEX IX_ALERTA_Expediente ON ALERTA(Expediente_ID);
CREATE INDEX IX_ALERTA_FechaAlerta ON ALERTA(FechaAlerta);
CREATE INDEX IX_ALERTA_Estado ON ALERTA(Estado);
CREATE INDEX IX_ALERTA_Leida ON ALERTA(Leida);
CREATE INDEX IX_ALERTA_Tipo ON ALERTA(TipoAlerta);
CREATE INDEX IX_ALERTA_Evento ON ALERTA(Evento_ID);
GO

-- 8.2 CONFIGURACION
CREATE TABLE CONFIGURACION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Clave NVARCHAR(50) NOT NULL UNIQUE,
    Valor NVARCHAR(MAX) NOT NULL,
    Descripcion NVARCHAR(200) NULL,
    FechaModificacion DATETIME NOT NULL DEFAULT GETDATE(),
    Usuario_ID INT NOT NULL,
    CONSTRAINT FK_CONFIGURACION_USUARIO FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
);
CREATE INDEX IX_CONFIGURACION_Clave ON CONFIGURACION(Clave);
GO

-- ------------------------------------------------------------
-- 2. Modulos y matriz de permisos por rol (ScriptsDB/01-Usuarios_Permisos.sql)
-- ------------------------------------------------------------
-- 1. Tabla MODULO (catálogo fijo)
IF OBJECT_ID('dbo.MODULO', 'U') IS NULL
BEGIN
    CREATE TABLE MODULO (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        Nombre NVARCHAR(50) NOT NULL,
        Clave NVARCHAR(50) NOT NULL UNIQUE,
        Icono NVARCHAR(50) NULL,
        Ruta NVARCHAR(100) NULL,
        Orden INT NOT NULL DEFAULT 0,
        Activo BIT NOT NULL DEFAULT 1
    );
END
GO

-- 2. Tabla PERMISO_ROL (solo activo/inactivo)
IF OBJECT_ID('dbo.PERMISO_ROL', 'U') IS NULL
BEGIN
    CREATE TABLE PERMISO_ROL (
        Rol_ID INT NOT NULL,
        Modulo_ID INT NOT NULL,
        Activo BIT NOT NULL DEFAULT 0,
        CONSTRAINT PK_PERMISO_ROL PRIMARY KEY (Rol_ID, Modulo_ID),
        CONSTRAINT FK_PERMISO_ROL_ROL FOREIGN KEY (Rol_ID) REFERENCES ROL(ID) ON DELETE CASCADE,
        CONSTRAINT FK_PERMISO_ROL_MODULO FOREIGN KEY (Modulo_ID) REFERENCES MODULO(ID) ON DELETE CASCADE
    );
END
GO

-- ------------------------------------------------------------
-- 3. Auditoria de hash de contrasenas en USUARIO (ScriptsDB/02-Seguridad.sql)
-- ------------------------------------------------------------
-- ============================================================
-- PARTE 1: COLUMNAS DE AUDITORIA DE HASH
-- ============================================================

-- 1.1 Agregar columna HashLegacy a USUARIO
--     Indica si el hash de la contraseña aún usa SHA256 (legacy)
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('USUARIO') AND name = 'HashLegacy'
)
BEGIN
    ALTER TABLE USUARIO ADD HashLegacy BIT NOT NULL DEFAULT 1;
END
GO

-- 1.2 Agregar columna FechaUltimoCambioHash a USUARIO
--     Registra cuándo se migró el hash a BCrypt
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('USUARIO') AND name = 'FechaUltimoCambioHash'
)
BEGIN
    ALTER TABLE USUARIO ADD FechaUltimoCambioHash DATETIME NULL;
END
GO


-- ------------------------------------------------------------
-- 4. Refresh tokens y blacklist de JWT (ScriptsDB/02-Seguridad.sql)
-- ------------------------------------------------------------
-- ============================================================
-- PARTE 2: TABLA REFRESH_TOKEN
-- ============================================================

IF NOT EXISTS (
    SELECT 1 FROM sys.tables WHERE name = 'REFRESH_TOKEN'
)
BEGIN
    CREATE TABLE REFRESH_TOKEN (
        ID              INT IDENTITY(1,1) PRIMARY KEY,
        Usuario_ID      INT NOT NULL,
        TokenHash       NVARCHAR(255) NOT NULL,
        FechaCreacion   DATETIME NOT NULL DEFAULT GETDATE(),
        FechaExpiracion DATETIME NOT NULL,
        Revocado        BIT NOT NULL DEFAULT 0,
        FechaRevocacion DATETIME NULL,
        ReemplazadoPor  NVARCHAR(255) NULL,
        UserAgent       NVARCHAR(500) NULL,
        IPAddress       NVARCHAR(45) NULL,
        CONSTRAINT FK_REFRESH_TOKEN_USUARIO
            FOREIGN KEY (Usuario_ID) REFERENCES USUARIO(ID)
            ON DELETE CASCADE
    );

    CREATE UNIQUE INDEX IX_REFRESH_TOKEN_TokenHash
        ON REFRESH_TOKEN(TokenHash);

    CREATE INDEX IX_REFRESH_TOKEN_Usuario
        ON REFRESH_TOKEN(Usuario_ID, Revocado);

    CREATE INDEX IX_REFRESH_TOKEN_Expiracion
        ON REFRESH_TOKEN(FechaExpiracion);
END
GO

-- ============================================================
-- PARTE 3: TABLA TOKEN_BLACKLIST
-- ============================================================

IF NOT EXISTS (
    SELECT 1 FROM sys.tables WHERE name = 'TOKEN_BLACKLIST'
)
BEGIN
    CREATE TABLE TOKEN_BLACKLIST (
        JTI              NVARCHAR(50) PRIMARY KEY,
        Usuario_ID       INT NOT NULL,
        FechaExpiracion  DATETIME NOT NULL,
        FechaRevocacion  DATETIME NOT NULL DEFAULT GETDATE(),
        Motivo           NVARCHAR(200) NULL
    );

    CREATE INDEX IX_TOKEN_BLACKLIST_Expiracion
        ON TOKEN_BLACKLIST(FechaExpiracion);
END
GO

-- ------------------------------------------------------------
-- 5. Restriccion unica de audiencias (ScriptsDB/08-Audiencias-UniqueConstraint.sql)
-- ------------------------------------------------------------
-- ============================================
-- Migracion: Agregar restriccion unica en AUDIENCIA
-- Previene duplicados de audiencias por mismo expediente, fecha y hora
-- ============================================

-- Restriccion unica: un expediente no puede tener dos audiencias
-- en la misma fecha y hora de inicio
ALTER TABLE AUDIENCIA
ADD CONSTRAINT UQ_AUDIENCIA_EXPEDIENTE_FECHA_HORA
UNIQUE (Expediente_ID, Fecha, HoraInicio);

-- Indice para mejorar rendimiento de consultas por expediente y fecha
CREATE INDEX IX_AUDIENCIA_EXPEDIENTE_FECHA ON AUDIENCIA (Expediente_ID, Fecha);

-- ------------------------------------------------------------
-- 6. Catalogo de resultados de diligencia (ScriptsDB/19-Diligencias-Resultado.sql)
-- ------------------------------------------------------------
-- 19.1 Catálogo RESULTADO_DILIGENCIA
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RESULTADO_DILIGENCIA')
BEGIN
    CREATE TABLE RESULTADO_DILIGENCIA (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        Nombre NVARCHAR(50) NOT NULL UNIQUE,
        Valor NVARCHAR(20) NULL,
        Descripcion NVARCHAR(200) NULL,
        Color NVARCHAR(7) NULL,
        Orden INT NOT NULL DEFAULT 0,
        Activo BIT NOT NULL DEFAULT 1,
        FechaCreacion DATETIME NOT NULL DEFAULT GETDATE()
    );
    CREATE INDEX IX_RESULTADO_DILIGENCIA_Nombre ON RESULTADO_DILIGENCIA(Nombre);
    CREATE INDEX IX_RESULTADO_DILIGENCIA_Activo ON RESULTADO_DILIGENCIA(Activo);
END
GO
-- 19.2 Columnas de resultado en DILIGENCIA
IF COL_LENGTH('DILIGENCIA', 'Resultado_ID') IS NULL
BEGIN
    ALTER TABLE DILIGENCIA ADD Resultado_ID INT NULL;
    ALTER TABLE DILIGENCIA ADD CONSTRAINT FK_DILIGENCIA_RESULTADO_DILIGENCIA
        FOREIGN KEY (Resultado_ID) REFERENCES RESULTADO_DILIGENCIA(ID);
END
GO

IF COL_LENGTH('DILIGENCIA', 'DescripcionResultado') IS NULL
BEGIN
    ALTER TABLE DILIGENCIA ADD DescripcionResultado NVARCHAR(1000) NULL;
END
GO

